algoritmo "exercico de fixação 2"

var
cod:caracter
inicio
escreval("escreva o código")
leia(cod)

      escolha(cod)
        caso "O"
         escreval("tipo de veiculo:ônibus  Pedágio:R$20,00")
        caso "C"
         escreval("tipo de veiculo:caminhão  Pedágio:R$15,00")
        caso "M"
         escreval("tipo de veiculo:moto  Pedágio:R$3,00")
        caso "V"
         escreval("tipo de veiculo:veículo de passeio  Pedágio:R$8,00")
      fimescolha
fimalgoritmo
