algoritmo "semnome"
// Função :
// Autor :
// Data : 30/05/2014
// Seção de Declarações 
var
litros: real
inicio
escreval("quantidade de litros")
leia(litros)
se (litros<10) entao
escreval("Voce ganho um CHAVEIRO")
senao (10<=litros<=30) entao
escreval("Voce ganhou uma DUCHA")
FIMSE
se (litros>30) entao
escreval("Voce ganho uma DUCHA e TROCA DE OLEO!!")
FIMSE

// Seção de Comandos 
fimalgoritmo
